"""
PDF Report Generator — Creates a clinical summary PDF aimed at healthcare professionals using ReportLab.
"""
from io import BytesIO
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib.colors import HexColor
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT

def generate_report(
    condition: str,
    confidence: int,
    risk_tier: str,
    explanation_doctor: str,
    warning_signs: list[str],
    urgency: str,
    specialist: str,
    reasoning: list[str],
) -> bytes:
    """
    Generate a one-page doctor-centric clinical handover PDF.

    Returns:
        PDF as bytes, ready to serve as a download.
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=1.5 * cm,
        bottomMargin=1.5 * cm,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=18,
        textColor=HexColor("#0f172a"),
        spaceAfter=2,
    )
    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=HexColor("#64748b"),
        alignment=TA_CENTER,
        spaceAfter=12,
    )
    heading_style = ParagraphStyle(
        "CustomHeading",
        parent=styles["Heading2"],
        fontSize=12,
        textColor=HexColor("#1e293b"),
        spaceBefore=14,
        spaceAfter=4,
        fontName="Helvetica-Bold",
        borderPadding=(0, 0, 4, 0),
        borderColor=HexColor("#e2e8f0"),
        borderWidth=0.5,
    )
    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=9.5,
        leading=14,
        textColor=HexColor("#334155"),
    )
    list_style = ParagraphStyle(
        "ListItem",
        parent=body_style,
        leftIndent=12,
        bulletColor=HexColor("#3b82f6"),
        spaceAfter=2,
    )
    alert_style = ParagraphStyle(
        "AlertItem",
        parent=body_style,
        leftIndent=12,
        bulletColor=HexColor("#ef4444"),
        textColor=HexColor("#991b1b"),
        spaceAfter=2,
    )
    disclaimer_style = ParagraphStyle(
        "Disclaimer",
        parent=styles["Normal"],
        fontSize=8,
        textColor=HexColor("#94a3b8"),
        alignment=TA_CENTER,
        spaceBefore=20,
    )
    badge_style = ParagraphStyle(
        "Badge",
        parent=styles["Normal"],
        fontSize=10,
        fontName="Helvetica-Bold",
        spaceAfter=8,
    )

    elements = []

    # Header
    elements.append(Paragraph("CLINICAL AI HANDOVER REPORT", title_style))
    elements.append(Paragraph(
        f"Generated on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
        subtitle_style,
    ))
    elements.append(Spacer(1, 10))

    # Triage & Primary Hypothesis
    risk_colors = {
        "low": "#10b981", "medium": "#f59e0b",
        "high": "#f97316", "critical": "#ef4444"
    }
    risk_color = risk_colors.get(risk_tier, "#64748b")

    elements.append(Paragraph("Primary Diagnostic Hypothesis", heading_style))
    elements.append(Paragraph(
        f'<font size="14" color="{risk_color}"><b>{condition}</b></font>'
        f'&nbsp;&nbsp;<font size="10" color="#64748b">(AI Confidence: {confidence}% | Triage Tier: {risk_tier.upper()})</font>',
        badge_style,
    ))
    elements.append(Paragraph(
        f"<b>Suggested Urgency:</b> {urgency.title() if urgency else 'Routine Evaluation'}<br/>"
        f"<b>Recommended Referral/Specialist:</b> {specialist if specialist else 'General Practice / PCP'}",
        body_style
    ))
    elements.append(Spacer(1, 8))

    # Clinical Summary (Doctor-centric explanation, differentials, workup)
    elements.append(Paragraph("Clinical Summary & Workup Recommendations", heading_style))
    elements.append(Paragraph(explanation_doctor.replace("\n", "<br/>"), body_style))
    elements.append(Spacer(1, 8))

    # Red Flags / Warning Signs
    if warning_signs:
        elements.append(Paragraph("Red Flags / Warning Signs Indicated", heading_style))
        for item in warning_signs:
            elements.append(Paragraph(f"• {item}", alert_style))
        elements.append(Spacer(1, 8))

    # Reasoning Chain
    if reasoning:
        elements.append(Paragraph("AI Clinical Reasoning Chain", heading_style))
        for i, step in enumerate(reasoning, 1):
            elements.append(Paragraph(f"{i}. {step}", list_style))
        elements.append(Spacer(1, 8))

    # Footer Disclaimer
    elements.append(Spacer(1, 20))
    elements.append(HRFlowable(width="100%", thickness=0.5, color=HexColor("#e2e8f0")))
    elements.append(Paragraph(
        "⚕️ This report contains preliminary findings generated by the Meowmeow AI clinical engine via patient interview. "
        "It is designed to assist healthcare professionals by summarizing patient symptomatology, aggregating clinical probabilities, "
        "and suggesting differentials. It is NOT a substitute for professional medical judgment, physical examination, or diagnostic testing.",
        disclaimer_style,
    ))

    doc.build(elements)
    return buffer.getvalue()
