"""
PDF Report Generator — Creates a clinical summary PDF using ReportLab.
"""
from io import BytesIO
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib.colors import HexColor
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT


def generate_report(
    condition: str,
    confidence: int,
    risk_tier: str,
    explanation: str,
    dos: list[str],
    donts: list[str],
    see_doctor: bool,
    see_doctor_reason: str = "",
    reasoning: list[str] = None,
) -> bytes:
    """
    Generate a one-page clinical summary PDF.

    Returns:
        PDF as bytes, ready to serve as a download.
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=1.5 * cm,
        bottomMargin=1.5 * cm,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=22,
        textColor=HexColor("#0f172a"),
        spaceAfter=4,
    )
    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=HexColor("#64748b"),
        alignment=TA_CENTER,
        spaceAfter=16,
    )
    heading_style = ParagraphStyle(
        "CustomHeading",
        parent=styles["Heading2"],
        fontSize=13,
        textColor=HexColor("#1e293b"),
        spaceBefore=14,
        spaceAfter=6,
    )
    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=10,
        leading=15,
        textColor=HexColor("#334155"),
    )
    do_style = ParagraphStyle(
        "DoItem",
        parent=body_style,
        leftIndent=12,
        bulletColor=HexColor("#10b981"),
    )
    dont_style = ParagraphStyle(
        "DontItem",
        parent=body_style,
        leftIndent=12,
        bulletColor=HexColor("#ef4444"),
    )
    disclaimer_style = ParagraphStyle(
        "Disclaimer",
        parent=styles["Normal"],
        fontSize=8,
        textColor=HexColor("#94a3b8"),
        alignment=TA_CENTER,
        spaceBefore=20,
    )

    elements = []

    # Header
    elements.append(Paragraph("Meowmeow — Clinical Summary", title_style))
    elements.append(Paragraph(
        f"Generated on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
        subtitle_style,
    ))
    elements.append(HRFlowable(width="100%", thickness=1, color=HexColor("#e2e8f0")))
    elements.append(Spacer(1, 10))

    # Condition + Confidence
    risk_colors = {
        "low": "#10b981", "medium": "#f59e0b",
        "high": "#f97316", "critical": "#ef4444"
    }
    risk_color = risk_colors.get(risk_tier, "#64748b")

    elements.append(Paragraph(f"Detected Condition", heading_style))
    elements.append(Paragraph(
        f'<font size="16" color="{risk_color}"><b>{condition}</b></font>'
        f'&nbsp;&nbsp;<font size="10" color="#64748b">({confidence}% confidence — {risk_tier.upper()} risk)</font>',
        body_style,
    ))
    elements.append(Spacer(1, 6))
    elements.append(Paragraph(explanation, body_style))

    # Do's
    elements.append(Paragraph("✅ Recommended Actions (Do's)", heading_style))
    for item in dos:
        elements.append(Paragraph(f"• {item}", do_style))

    # Don'ts
    elements.append(Paragraph("❌ Things to Avoid (Don'ts)", heading_style))
    for item in donts:
        elements.append(Paragraph(f"• {item}", dont_style))

    # Doctor recommendation
    if see_doctor:
        elements.append(Paragraph("⚠️ Doctor Recommendation", heading_style))
        elements.append(Paragraph(
            f'<font color="#ef4444"><b>Professional medical attention is recommended.</b></font><br/>'
            f'{see_doctor_reason}',
            body_style,
        ))

    # Reasoning chain
    if reasoning:
        elements.append(Paragraph("🧠 Clinical Reasoning", heading_style))
        for i, step in enumerate(reasoning, 1):
            elements.append(Paragraph(f"{i}. {step}", body_style))

    # Disclaimer
    elements.append(Spacer(1, 20))
    elements.append(HRFlowable(width="100%", thickness=0.5, color=HexColor("#e2e8f0")))
    elements.append(Paragraph(
        "⚕️ This report is generated by Meowmeow AI Health Advisor and is for informational purposes only. "
        "It is NOT a medical diagnosis. Always consult a qualified healthcare professional for medical advice. "
        "Do not use this report as a substitute for professional medical judgment.",
        disclaimer_style,
    ))

    doc.build(elements)
    return buffer.getvalue()
